[package]
name = "vacancy"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
chrono = { version = "0.4.41", features = ["serde"]}
deadpool-postgres = { version = "0.14.1", features = ["rt_tokio_1"] }

# Crate compartido
shared = { path = "../shared" }

[lib]
path = "src/lib.rs"