version: '3.8'

services:
  app:
    build: .
    container_name: recursos_humanos_api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=info
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: recursos_humanos_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: